[features]
seeds = false
[programs.devnet]
sol_t = "DZyZ4HaJQ4kHXoPVFJARnC1gV7NzbujtPJRBu9Hcei3d"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/mort1b/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
